# Generated by Django 5.1.3 on 2025-02-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='rut',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='equiposeguridad',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='equiposeguridad',
            name='tipo',
            field=models.CharField(choices=[('Prevención', 'Prevención y Detección'), ('EPP', 'Equipo de Protección Personal'), ('Respuesta', 'Respuesta y Mitigación'), ('Comunicación', 'Comunicación de Emergencia'), ('Evacuación', 'Evacuación y Rescate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='planemergencia',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=50),
        ),
    ]
