# Generated by Django 5.1.3 on 2025-02-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_obra_imagen_alter_contratista_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planemergencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planes/'),
        ),
    ]
