# Generated by Django 5.1.3 on 2025-02-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_alter_planemergencia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planemergencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='plan_imagenes/'),
        ),
    ]
