# Generated by Django 5.1.3 on 2025-02-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_planemergencia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contratistas/'),
        ),
    ]
