# Generated by Django 5.1.3 on 2025-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_contratista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposeguridad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipo_imagenes/'),
        ),
    ]
